name: Auto-merge Semantic Release PRs

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'github-actions[bot]' }}  # Only act on PRs created by GitHub Actions bot

    steps:
      - name: Auto-approve the PR
        run: gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token to approve the PR

      - name: Auto-merge the PR
        run: gh pr merge ${{ github.event.pull_request.number }} --rebase --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token to merge the PR
