name: Release
on:
  workflow_run:
    workflows: ["Run Sanity Check"]
    types:
      - completed
    branches:
      - main

permissions:  # Ensure the token has the correct permissions
  contents: write
  issues: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH for deploy key
        uses: webfactory/ssh-agent@v0.5.3  # This action sets up the SSH agent for GitHub Actions
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
