name: Run Sanity Check

on:
  push:
    branches:
      - '**'  # Run on every branch for each push

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu version

    steps:
      - name: Checkout code  # Checkout the code from the repo
        uses: actions/checkout@v2

      - name: Set up Node.js  # Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Use Node.js version 22

      - name: Install dependencies  # Install npm dependencies
        run: npm ci

      - name: Run "Sanity Checks"  # Run the tests and validate style/formatting
        run: npm run sanity-check
